# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Nicholas Quirk
email: nquirk9@gmail.com
url: "https://nicholasquirk.github.io"
baseurl: /site 
description: > # this means to ignore newlines until "url:"
  A simple, whitespace theme for academics. Based on [*folio](https://github.com/bogoli/-folio) design.
footer_text: #pizza


last_updated: # never
# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: nquirk
linkedin_username: nicholas-quirk-581bb4107
scholar_authorid: F4uD8KcAAAAJ&hl
contact_note:


# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Ideas for the Future
blog_description: Things to consider now and act on later

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: al-folio # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge

# Includes
include: ['_pages']

#Plugins
Plugins:
    - Jekyll-seo-tag

# Gems
gems:
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:

  last_name: Einstein

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.7.1"
anchorjs_version: "3.2.2"
